apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitcloud-app-deployment
  namespace: orbitcloud
  labels:
    app: orbitcloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitcloud-app
  template:
    metadata:
      labels:
        app: orbitcloud-app
    spec:
      containers:
      - name: orbitcloud-app-container
        image: localhost:5000/orbitcloud-app:v1.12
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: orbitcloud-app
  namespace: orbitcloud
spec:
  selector:
    app: orbitcloud-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbitcloud-app-ingress
  namespace: orbitcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - app.orbitcloud.com.br
    secretName: orbitsender-tls-secret
  rules:
  - host: app.orbitcloud.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orbitcloud-app
            port:
              number: 8080