apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitcloud-db-deployment
  namespace: orbitcloud
  labels:
    app: orbitcloud-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitcloud-db
  template:
    metadata:
      labels:
        app: orbitcloud-db
    spec:
      containers:
      - name: orbitcloud-db-container
        image: localhost:5000/orbitcloud-db:v0.0.0
        ports:
        - containerPort: 8080
        volumesMounts:
        - name: db-data
          mountPath: /data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: orbitcloud-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orbitcloud-db-service
  namespace: orbitcloud
spec:
  selector:
    app: orbitcloud-db
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbitcloud-db-ingress
  namespace: orbitcloud
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - db.orbitcloud.com.br
      secretName: orbitcloud-tls-secret
  rules:
    - host: db.orbitcloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orbitcloud-db-service
                port:
                  number: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orbitcloud-db-pvc
  namespace: orbitcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard