apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitcloud-ui-deployment
  namespace: orbitcloud
  labels:
    app: orbitcloud-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitcloud-ui
  template:
    metadata:
      labels:
        app: orbitcloud-ui
    spec:
      containers:
      - name: orbitcloud-ui-container
        image: localhost:5000/orbitcloud-ui:v0.0.47
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orbitcloud-ui-service
  namespace: orbitcloud
spec:
  selector:
    app: orbitcloud-ui
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbitcloud-ui-ingress
  namespace: orbitcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - orbitcloud.com.br
      secretName: orbitnet-default-cert 
  rules:
    - host: orbitcloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orbitcloud-ui-service
                port:
                  number: 3000